export const TYPE_GUARD_DATA = [
  {
    id: 1,
    name: 'Tom',
    age: 18,
    job: 'student',
    grades: [85, 90, 78],
    lastLoginDate: new Date('2024-03-15'),
    contact: {
      email: 'tom@example.com',
      phone: 1234567890,
    },
  },
  {
    id: 2,
    name: 'Jacob',
    age: 34,
    job: 'teacher',
    subjects: ['Math', 'Physics'],
    lastLoginDate: '2024-03-14',
    contact: 'jacob@example.com',
  },
  {
    id: 3,
    nickName: 'Doctor.D',
    age: 49,
    hobby: 'watching movie',
    lastLoginDate: new Date('2024-03-13'),
    contact: 9876543210,
  },
  {
    id: 4,
    nickName: 'Jamilla',
    age: 24,
    hobby: 'reading books',
    booksRead: 150,
    lastLoginDate: '2024-03-12',
    contact: {
      email: 'jamilla@example.com',
      address: '123 Book St, Reading City',
    },
  },
  {
    id: 5,
    name: 'Sophia',
    age: 29,
    job: 'scientist',
    lastLoginDate: new Date('2024-03-11'),
    contact: ['sophia@example.com', 'sophia@university.edu'],
  },
];
